import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LandingLang = "en" | "it" | "de" | "fr";

const detectLanguage = (): LandingLang => {
  const browserLang = navigator.language?.toLowerCase() || "";
  if (browserLang.startsWith("it")) return "it";
  if (browserLang.startsWith("de")) return "de";
  if (browserLang.startsWith("fr")) return "fr";
  return "en";
};

interface LandingLanguageContextType {
  lang: LandingLang;
  setLang: (lang: LandingLang) => void;
  t: (key: string) => string;
}

const LandingLanguageContext = createContext<LandingLanguageContextType | null>(null);

export const useLandingLang = () => {
  const ctx = useContext(LandingLanguageContext);
  if (!ctx) throw new Error("useLandingLang must be used within LandingLanguageProvider");
  return ctx;
};

// Flat key-value translations
const translations: Record<LandingLang, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.features": "Features",
    "nav.dashboard": "Dashboard",
    "nav.pricing": "Pricing",
    "nav.login": "Log in",
    "nav.signup": "Get Started",
    "nav.widgetBuilder": "Widget Builder",
    "nav.widgetBuilderDesc": "Drag-and-drop interface to create widgets in minutes",
    "nav.liveChat": "Live Chat",
    "nav.liveChatDesc": "Engage visitors with real-time conversations",
    "nav.analytics": "Analytics",
    "nav.analyticsDesc": "Track engagement and conversion rates in real time",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.privacy": "Privacy",
    "nav.terms": "Terms",

    // Hero
    "hero.badge": "Now with AI-powered responses",
    "hero.title1": "Widgets that turn",
    "hero.title2": "visitors into customers",
    "hero.subtitle": "Create no-code website widgets for live chat, FAQs & sales. Customize everything, then add to any site with one line of code.",
    "hero.cta": "Start for Free",
    "hero.note1": "Free forever.",
    "hero.note2": "No credit card.",
    "hero.demo": "Show me live demo",

    // Logos
    "logos.heading": "Trusted by 100+ businesses worldwide",

    // Features
    "features.title1": "Everything you need,",
    "features.title2": "nothing you don't",
    "features.1.title": "Fully Customizable",
    "features.1.desc": "Design your perfect widget with an intuitive visual editor. Change colors, fonts, layouts, inject custom CSS & JavaScript — full customization with zero coding. Preview every change in real time.",
    "features.2.title": "FAQ Template",
    "features.2.desc": "Reduce support requests by up to 40% with a smart FAQ widget. Add unlimited questions, customize the design to match your brand, and give every visitor instant self-service — 24/7, on any page.",
    "features.3.title": "Product Cards",
    "features.3.desc": "Grab your visitors' attention with stunning product cards. Just paste a link to any product and we'll do the rest — beautiful cards, ready to convert in seconds.",

    // Dashboard
    "dashboard.label": "Dashboard",
    "dashboard.title": "One place for everything",
    "dashboard.desc": "Manage all your widgets, conversations, and analytics from a single intuitive dashboard.",

    // Platform
    "platform.title": "Instant integration",
    "platform.desc": "Just copy the widget code and paste it into your site — works with any platform, no setup needed.",

    // Pricing
    "pricing.title": "Simple, fair",
    "pricing.titleFaded": "pricing",
    "pricing.guarantee": "100% Money-back Guarantee",
    "pricing.saveYearly": "Save up to 20% with yearly",
    "pricing.priceIn": "Price in",
    "pricing.monthly": "Pay monthly",
    "pricing.yearly": "Pay yearly",
    "pricing.billedYearly": "Billed yearly",
    "pricing.billedMonthly": "Billed monthly",
    "pricing.forever": "forever",
    "pricing.free.name": "Free",
    "pricing.free.desc": "Perfect for individuals that want to start and try things out.",
    "pricing.free.cta": "Sign Up",
    "pricing.free.featuresLabel": "Key features:",
    "pricing.free.f1": "1 AI widget",
    "pricing.free.f2": "100 AI responses/mo",
    "pricing.free.f3": "Customizable theme & colors",
    "pricing.free.f4": "Contact card",
    "pricing.free.f5": "WhatsApp integration",
    "pricing.free.f6": "FAQ section",
    "pricing.free.f7": "Product carousel",
    "pricing.free.f8": "Escalate to human",
    "pricing.free.f9": "24/7 support (limited time)",
    "pricing.starter.name": "Starter",
    "pricing.starter.desc": "For individuals & side projects",
    "pricing.starter.cta": "Get Started",
    "pricing.starter.featuresLabel": "Everything in Free",
    "pricing.starter.f1": "3 AI widgets",
    "pricing.starter.f2": "500 AI responses/mo",
    "pricing.starter.f3": "Basic analytics",
    "pricing.starter.f4": "Instagram integration",
    "pricing.starter.f5": "Google Reviews widget",
     "pricing.pro.name": "Plus",
    "pricing.biz.name": "Business",
    "pricing.biz.desc": "For large teams looking for powerful and customizable AI support.",
    "pricing.biz.cta": "Get Started",
    "pricing.biz.featuresLabel": "Everything in Plus",
    "pricing.biz.f1": "10 AI widgets",
    "pricing.biz.f2": "10,000 AI responses/mo",
    "pricing.biz.f3": "Advanced analytics",
    "pricing.biz.f4": "Custom branding",
    "pricing.biz.f5": "Priority support",
    "pricing.biz.f6": "Team collaboration",
    "pricing.pro.desc": "For growing businesses that need advanced support & scalability.",
    "pricing.pro.cta": "Get Started",
    "pricing.pro.badge": "Popular",
    "pricing.pro.featuresLabel": "Everything in Free",
    "pricing.pro.f1": "3 AI widgets",
    "pricing.pro.f2": "2,000 AI responses/mo",
    "pricing.pro.f3": "AI summaries",
    "pricing.pro.f4": "Advanced analytics",
    "pricing.pro.f5": "24/7 Priority support",
    "pricing.pro.f6": "Custom branding",
    "pricing.pro.f7": "Widget size & position control",
    "pricing.pro.f8": "Team collaboration (coming soon)",
    "pricing.business.name": "Enterprise",
    "pricing.business.desc": "For organizations needing high-volume support & custom integrations.",
    "pricing.business.cta": "Contact Sales",
    "pricing.business.featuresLabel": "Everything in Business",
    "pricing.business.f1": "Unlimited conversations",
    "pricing.business.f2": "API access",
    "pricing.business.f3": "Dedicated account manager",
    "pricing.business.f4": "SLA guarantee",
    "pricing.business.f5": "SSO & advanced security",
    "pricing.business.f6": "White labeling",

    // FAQs
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Quick answers to the most common questions about Widjet.",
    "faq.q1": "What is Widjet and how does it work?",
    "faq.a1": "Widjet is a SaaS platform that lets you build beautiful support & sales widgets for your website. You design your widget in our visual editor, customize every detail, and publish it with a single line of code — no developers needed.",
    "faq.q2": "How do I add a widget to my website?",
    "faq.a2": "Once you've created your widget, we generate a single <script> tag. Paste it anywhere in your site's HTML and the widget appears instantly. It works with WordPress, Shopify, Webflow, Squarespace, and any custom-built site.",
    "faq.q3": "Can I fully customize the look and feel?",
    "faq.a3": "Yes — colors, fonts, position, icons, animations, and even custom CSS are all configurable. On Pro and Business plans you can also remove the Widjet branding for a fully white-label experience.",
    "faq.q4": "How does the AI-powered response feature work?",
    "faq.a4": "Widjet's AI reads your knowledge base and automatically drafts replies to common visitor questions. It learns over time and can reduce your support workload by up to 60%, so your team can focus on complex issues.",
    "faq.q5": "Is there a free plan?",
    "faq.a5": "Absolutely. The Free plan includes 1 widget and 100 conversations per month — forever. No credit card required. When you're ready to scale, you can upgrade to Pro or Business at any time.",
    "faq.q6": "Can I use multiple widgets on different pages?",
    "faq.a6": "Yes! On Pro and Business plans you can create unlimited widgets, each with its own design and behavior. Assign different widgets to different pages or domains from a single dashboard.",
    "faq.q7": "What kind of analytics do I get?",
    "faq.a7": "Widjet tracks conversation volume, response times, visitor satisfaction, and conversion events. Pro plans include advanced analytics with funnel breakdowns and exportable reports.",
    "faq.contact": "Can't find what you're looking for?",
    "faq.contactLink": "Contact our support team",

    // Footer CTA
    "footer.ctaTitle1": "Ready to engage",
    "footer.ctaTitle2": "your visitors?",
    "footer.ctaDesc": "Join 2,000+ businesses already using Widjet to connect with their customers.",
    "footer.ctaCta": "Start for Free",
    "footer.ctaNote": "Free forever. No credit card required.",
    "footer.madeInEu": "Made and hosted in the EU 🇪🇺",
    // Footer columns
    "footer.product": "Product",
    "footer.widgetBuilder": "Widget Builder",
    "footer.liveChat": "Live Chat",
    "footer.analytics": "Analytics",
    "footer.integrations": "Integrations",
    "footer.resources": "Resources",
    "footer.helpCenter": "Help center",
    "footer.pricing": "Pricing",
    "footer.company": "Company",
    "footer.security": "Security",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "footer.contact": "Contact",
    "footer.widjetFor": "Widjet for",
    "footer.ecommerce": "E-commerce",
    "footer.smallBusiness": "Small business",
    "footer.agencies": "Agencies",

    // Compare table
    "compare.title": "Plans and features",
    "compare.catCore": "Core",
    "compare.catAdvanced": "Advanced",
    "compare.catEnterprise": "Enterprise",
    "compare.unlimited": "Unlimited",
    "compare.basic": "Basic",
    "compare.advanced": "Advanced",
    "compare.aiWidgets": "AI widgets",
    "compare.aiResponses": "AI responses / month",
    "compare.contactCard": "Contact card",
    "compare.whatsapp": "WhatsApp integration",
    "compare.faq": "FAQ section",
    "compare.productCarousel": "Product carousel",
    "compare.escalate": "Escalate to human",
    "compare.aiSummaries": "AI summaries",
    "compare.analytics": "Analytics",
    "compare.customBranding": "Custom branding",
    "compare.sizePosition": "Widget size & position",
    "compare.instagram": "Instagram integration",
    "compare.googleReviews": "Google Reviews widget",
    "compare.prioritySupport": "Priority support",
    "compare.teamCollab": "Team collaboration",
    "compare.apiAccess": "API access",
    "compare.accountManager": "Dedicated account manager",
    "compare.sla": "SLA guarantee",
    "compare.sso": "SSO & advanced security",
    "compare.whiteLabel": "White labeling",
  },

  it: {
    "nav.home": "Home",
    "nav.features": "Funzionalità",
    "nav.dashboard": "Dashboard",
    "nav.pricing": "Prezzi",
    "nav.login": "Accedi",
    "nav.signup": "Inizia Gratis",
    "nav.widgetBuilder": "Widget Builder",
    "nav.widgetBuilderDesc": "Interfaccia drag-and-drop per creare widget in pochi minuti",
    "nav.liveChat": "Chat dal Vivo",
    "nav.liveChatDesc": "Coinvolgi i visitatori con conversazioni in tempo reale",
    "nav.analytics": "Analisi",
    "nav.analyticsDesc": "Monitora engagement e tassi di conversione in tempo reale",
    "nav.blog": "Blog",
    "nav.contact": "Contatti",
    "nav.privacy": "Privacy",
    "nav.terms": "Termini",

    "hero.badge": "Ora con risposte AI",
    "hero.title1": "Widget che trasformano",
    "hero.title2": "i visitatori in clienti",
    "hero.subtitle": "Crea widget no-code per chat dal vivo, FAQ e vendite. Personalizza tutto, poi aggiungilo a qualsiasi sito con una riga di codice.",
    "hero.cta": "Inizia Gratis",
    "hero.note1": "Gratis per sempre.",
    "hero.note2": "Nessuna carta richiesta.",
    "hero.demo": "Mostrami una demo live",

    "logos.heading": "Scelto da oltre 200 aziende nel mondo",

    "features.title1": "Tutto ciò di cui hai bisogno,",
    "features.title2": "niente di superfluo",
    "features.1.title": "Completamente Personalizzabile",
    "features.1.desc": "Progetta il tuo widget perfetto con un editor visuale intuitivo. Cambia colori, font, layout, inietta CSS e JavaScript personalizzati — personalizzazione completa senza codice. Anteprima di ogni modifica in tempo reale.",
    "features.2.title": "Template FAQ",
    "features.2.desc": "Riduci le richieste di supporto fino al 40% con un widget FAQ intelligente. Aggiungi domande illimitate, personalizza il design per adattarlo al tuo brand e offri ai visitatori un self-service istantaneo — 24/7, su ogni pagina.",
    "features.3.title": "Schede Prodotto",
    "features.3.desc": "Cattura l'attenzione dei visitatori con splendide schede prodotto. Incolla un link a qualsiasi prodotto e faremo il resto — schede bellissime, pronte a convertire in pochi secondi.",

    "dashboard.label": "Dashboard",
    "dashboard.title": "Tutto in un unico posto",
    "dashboard.desc": "Gestisci tutti i tuoi widget, conversazioni e analisi da un'unica dashboard intuitiva.",

    "platform.title": "Integrazione immediata",
    "platform.desc": "Copia il codice del widget e incollalo nel tuo sito — funziona con qualsiasi piattaforma, senza configurazione.",

    "pricing.title": "Prezzi semplici e",
    "pricing.titleFaded": "trasparenti",
    "pricing.guarantee": "Garanzia soddisfatti o rimborsati 100%",
    "pricing.saveYearly": "Risparmia fino al 20% con l'annuale",
    "pricing.priceIn": "Prezzo in",
    "pricing.monthly": "Paga mensilmente",
    "pricing.yearly": "Paga annualmente",
    "pricing.billedYearly": "Fatturato annualmente",
    "pricing.billedMonthly": "Fatturato mensilmente",
    "pricing.forever": "per sempre",
    "pricing.free.name": "Free",
    "pricing.free.desc": "Perfetto per chi vuole iniziare e provare.",
    "pricing.free.cta": "Registrati",
    "pricing.free.featuresLabel": "Funzionalità principali:",
    "pricing.free.f1": "1 AI widget",
    "pricing.free.f2": "100 risposte AI/mese",
    "pricing.free.f3": "Tema e colori personalizzabili",
    "pricing.free.f4": "Scheda contatto",
    "pricing.free.f5": "Integrazione WhatsApp",
    "pricing.free.f6": "Sezione FAQ",
    "pricing.free.f7": "Carosello prodotti",
    "pricing.free.f8": "Escalation a operatore",
    "pricing.free.f9": "Supporto 24/7 (tempo limitato)",
    "pricing.starter.name": "Starter",
    "pricing.starter.desc": "Per individui e side project",
    "pricing.starter.cta": "Inizia Ora",
    "pricing.starter.featuresLabel": "Tutto in Free",
    "pricing.starter.f1": "3 AI widget",
    "pricing.starter.f2": "500 risposte AI/mese",
    "pricing.starter.f3": "Analisi base",
    "pricing.starter.f4": "Integrazione Instagram",
    "pricing.starter.f5": "Widget Google Reviews",
     "pricing.pro.name": "Plus",
    "pricing.biz.name": "Business",
    "pricing.biz.desc": "Per grandi team alla ricerca di un supporto AI potente e personalizzabile.",
    "pricing.biz.cta": "Inizia Ora",
    "pricing.biz.featuresLabel": "Tutto in Plus",
    "pricing.biz.f1": "10 AI widget",
    "pricing.biz.f2": "10.000 risposte AI/mese",
    "pricing.biz.f3": "Analisi avanzate",
    "pricing.biz.f4": "Branding personalizzato",
    "pricing.biz.f5": "Supporto prioritario",
    "pricing.biz.f6": "Collaborazione team",
    "pricing.pro.desc": "Per aziende in crescita che necessitano di supporto avanzato e scalabilità.",
    "pricing.pro.cta": "Inizia Ora",
    "pricing.pro.badge": "Popolare",
    "pricing.pro.featuresLabel": "Tutto in Free",
    "pricing.pro.f1": "3 AI widget",
    "pricing.pro.f2": "2.000 risposte AI/mese",
    "pricing.pro.f3": "AI summaries",
    "pricing.pro.f4": "Analisi avanzate",
    "pricing.pro.f5": "Supporto prioritario 24/7",
    "pricing.pro.f6": "Branding personalizzato",
    "pricing.pro.f7": "Controllo dimensioni e posizione widget",
    "pricing.pro.f8": "Collaborazione team (in arrivo)",
    "pricing.business.name": "Enterprise",
    "pricing.business.desc": "Per organizzazioni con supporto ad alto volume ed esigenze di integrazione personalizzate.",
    "pricing.business.cta": "Contatta Vendite",
    "pricing.business.featuresLabel": "Tutto in Business",
    "pricing.business.f1": "Conversazioni illimitate",
    "pricing.business.f2": "Accesso API",
    "pricing.business.f3": "Account manager dedicato",
    "pricing.business.f4": "Garanzia SLA",
    "pricing.business.f5": "SSO e sicurezza avanzata",
    "pricing.business.f6": "White labeling",

    "faq.title": "Domande Frequenti",
    "faq.subtitle": "Risposte rapide alle domande più comuni su Widjet.",
    "faq.q1": "Cos'è Widjet e come funziona?",
    "faq.a1": "Widjet è una piattaforma SaaS che ti permette di creare bellissimi widget di supporto e vendita per il tuo sito web. Progetti il widget nel nostro editor visuale, personalizzi ogni dettaglio e lo pubblichi con una sola riga di codice — senza sviluppatori.",
    "faq.q2": "Come aggiungo un widget al mio sito?",
    "faq.a2": "Dopo aver creato il widget, generiamo un singolo tag <script>. Incollalo ovunque nell'HTML del tuo sito e il widget appare istantaneamente. Funziona con WordPress, Shopify, Webflow, Squarespace e qualsiasi sito personalizzato.",
    "faq.q3": "Posso personalizzare completamente l'aspetto?",
    "faq.a3": "Sì — colori, font, posizione, icone, animazioni e persino CSS personalizzato sono tutti configurabili. Con i piani Pro e Business puoi anche rimuovere il branding Widjet per un'esperienza completamente white-label.",
    "faq.q4": "Come funziona la risposta AI?",
    "faq.a4": "L'AI di Widjet legge la tua knowledge base e redige automaticamente risposte alle domande comuni dei visitatori. Impara nel tempo e può ridurre il carico di lavoro del supporto fino al 60%, così il tuo team può concentrarsi su questioni complesse.",
    "faq.q5": "Esiste un piano gratuito?",
    "faq.a5": "Assolutamente. Il piano Free include 1 widget e 100 conversazioni al mese — per sempre. Nessuna carta di credito richiesta. Quando sei pronto, puoi passare a Pro o Business in qualsiasi momento.",
    "faq.q6": "Posso usare più widget su pagine diverse?",
    "faq.a6": "Sì! Con i piani Pro e Business puoi creare widget illimitati, ciascuno con il proprio design e comportamento. Assegna widget diversi a pagine o domini diversi da un'unica dashboard.",
    "faq.q7": "Che tipo di analisi ottengo?",
    "faq.a7": "Widjet traccia volume delle conversazioni, tempi di risposta, soddisfazione dei visitatori ed eventi di conversione. I piani Pro includono analisi avanzate con funnel e report esportabili.",
    "faq.contact": "Non trovi quello che cerchi?",
    "faq.contactLink": "Contatta il nostro supporto",

    "footer.ctaTitle1": "Pronto a coinvolgere",
    "footer.ctaTitle2": "i tuoi visitatori?",
    "footer.ctaDesc": "Unisciti a oltre 2.000 aziende che già usano Widjet per connettersi con i loro clienti.",
    "footer.ctaCta": "Inizia Gratis",
    "footer.ctaNote": "Gratis per sempre. Nessuna carta di credito richiesta.",
    "footer.madeInEu": "Creato e ospitato nell'UE 🇪🇺",
    "footer.product": "Prodotto",
    "footer.widgetBuilder": "Widget Builder",
    "footer.liveChat": "Chat dal Vivo",
    "footer.analytics": "Analisi",
    "footer.integrations": "Integrazioni",
    "footer.resources": "Risorse",
    "footer.helpCenter": "Centro Assistenza",
    "footer.pricing": "Prezzi",
    "footer.company": "Azienda",
    "footer.security": "Sicurezza",
    "footer.terms": "Termini di Servizio",
    "footer.privacy": "Privacy Policy",
    "footer.contact": "Contatti",
    "footer.widjetFor": "Widjet per",
    "footer.ecommerce": "E-commerce",
    "footer.smallBusiness": "Piccole imprese",
    "footer.agencies": "Agenzie",

    "compare.title": "Piani e funzionalità",
    "compare.catCore": "Base",
    "compare.catAdvanced": "Avanzate",
    "compare.catEnterprise": "Enterprise",
    "compare.unlimited": "Illimitati",
    "compare.basic": "Base",
    "compare.advanced": "Avanzate",
    "compare.aiWidgets": "AI widget",
    "compare.aiResponses": "Risposte AI / mese",
    "compare.contactCard": "Scheda contatto",
    "compare.whatsapp": "Integrazione WhatsApp",
    "compare.faq": "Sezione FAQ",
    "compare.productCarousel": "Carosello prodotti",
    "compare.escalate": "Escalation a operatore",
    "compare.aiSummaries": "AI summaries",
    "compare.analytics": "Analisi",
    "compare.customBranding": "Branding personalizzato",
    "compare.sizePosition": "Dimensioni e posizione widget",
    "compare.instagram": "Integrazione Instagram",
    "compare.googleReviews": "Widget Google Reviews",
    "compare.prioritySupport": "Supporto prioritario",
    "compare.teamCollab": "Collaborazione team",
    "compare.apiAccess": "Accesso API",
    "compare.accountManager": "Account manager dedicato",
    "compare.sla": "Garanzia SLA",
    "compare.sso": "SSO e sicurezza avanzata",
    "compare.whiteLabel": "White labeling",
  },

  de: {
    "nav.home": "Startseite",
    "nav.features": "Funktionen",
    "nav.dashboard": "Dashboard",
    "nav.pricing": "Preise",
    "nav.login": "Anmelden",
    "nav.signup": "Jetzt starten",
    "nav.widgetBuilder": "Widget Builder",
    "nav.widgetBuilderDesc": "Drag-and-Drop-Oberfläche zum Erstellen von Widgets in Minuten",
    "nav.liveChat": "Live-Chat",
    "nav.liveChatDesc": "Besucher mit Echtzeit-Gesprächen einbinden",
    "nav.analytics": "Analysen",
    "nav.analyticsDesc": "Engagement und Konversionsraten in Echtzeit verfolgen",
    "nav.blog": "Blog",
    "nav.contact": "Kontakt",
    "nav.privacy": "Datenschutz",
    "nav.terms": "AGB",

    "hero.badge": "Jetzt mit KI-gestützten Antworten",
    "hero.title1": "Widgets, die Besucher",
    "hero.title2": "in Kunden verwandeln",
    "hero.subtitle": "Erstellen Sie No-Code-Website-Widgets für Live-Chat, FAQ und Verkauf. Passen Sie alles an und fügen Sie es mit einer Zeile Code zu jeder Website hinzu.",
    "hero.cta": "Kostenlos starten",
    "hero.note1": "Für immer kostenlos.",
    "hero.note2": "Keine Kreditkarte nötig.",
    "hero.demo": "Live-Demo anzeigen",

    "logos.heading": "Von über 200 Unternehmen weltweit vertraut",

    "features.title1": "Alles was Sie brauchen,",
    "features.title2": "nichts Überflüssiges",
    "features.1.title": "Vollständig anpassbar",
    "features.1.desc": "Gestalten Sie Ihr perfektes Widget mit einem intuitiven visuellen Editor. Ändern Sie Farben, Schriftarten, Layouts, fügen Sie benutzerdefiniertes CSS & JavaScript ein — volle Anpassung ohne Programmierung. Vorschau jeder Änderung in Echtzeit.",
    "features.2.title": "FAQ-Vorlage",
    "features.2.desc": "Reduzieren Sie Support-Anfragen um bis zu 40% mit einem intelligenten FAQ-Widget. Fügen Sie unbegrenzt Fragen hinzu, passen Sie das Design an Ihre Marke an und bieten Sie Besuchern sofortigen Self-Service — 24/7, auf jeder Seite.",
    "features.3.title": "Produktkarten",
    "features.3.desc": "Fesseln Sie die Aufmerksamkeit Ihrer Besucher mit beeindruckenden Produktkarten. Fügen Sie einfach einen Link zu einem Produkt ein und wir erledigen den Rest — schöne Karten, in Sekunden konversionsbereit.",

    "dashboard.label": "Dashboard",
    "dashboard.title": "Alles an einem Ort",
    "dashboard.desc": "Verwalten Sie alle Ihre Widgets, Gespräche und Analysen über ein einziges intuitives Dashboard.",

    "platform.title": "Sofortige Integration",
    "platform.desc": "Kopieren Sie den Widget-Code und fügen Sie ihn in Ihre Website ein — funktioniert mit jeder Plattform, keine Einrichtung nötig.",

    "pricing.title": "Einfache, faire",
    "pricing.titleFaded": "Preise",
    "pricing.guarantee": "100% Geld-zurück-Garantie",
    "pricing.saveYearly": "Bis zu 20% sparen mit Jahresabo",
    "pricing.priceIn": "Preis in",
    "pricing.monthly": "Monatlich zahlen",
    "pricing.yearly": "Jährlich zahlen",
    "pricing.billedYearly": "Jährlich abgerechnet",
    "pricing.billedMonthly": "Monatlich abgerechnet",
    "pricing.forever": "für immer",
    "pricing.free.name": "Free",
    "pricing.free.desc": "Perfekt für Einzelpersonen, die starten und ausprobieren möchten.",
    "pricing.free.cta": "Registrieren",
    "pricing.free.featuresLabel": "Hauptfunktionen:",
    "pricing.free.f1": "1 KI-Widget",
    "pricing.free.f2": "100 KI-Antworten/Monat",
    "pricing.free.f3": "Anpassbares Theme & Farben",
    "pricing.free.f4": "Kontaktkarte",
    "pricing.free.f5": "WhatsApp-Integration",
    "pricing.free.f6": "FAQ-Bereich",
    "pricing.free.f7": "Produktkarussell",
    "pricing.free.f8": "Eskalation an Mitarbeiter",
    "pricing.free.f9": "24/7 Support (begrenzte Zeit)",
    "pricing.starter.name": "Starter",
    "pricing.starter.desc": "Für Einzelpersonen & Nebenprojekte",
    "pricing.starter.cta": "Jetzt starten",
    "pricing.starter.featuresLabel": "Alles in Free",
    "pricing.starter.f1": "3 KI-Widgets",
    "pricing.starter.f2": "500 KI-Antworten/Monat",
    "pricing.starter.f3": "Grundlegende Analysen",
    "pricing.starter.f4": "Instagram-Integration",
    "pricing.starter.f5": "Google Reviews Widget",
     "pricing.pro.name": "Plus",
    "pricing.biz.name": "Business",
    "pricing.biz.desc": "Für große Teams, die leistungsstarken und anpassbaren KI-Support suchen.",
    "pricing.biz.cta": "Jetzt starten",
    "pricing.biz.featuresLabel": "Alles in Plus",
    "pricing.biz.f1": "10 KI-Widgets",
    "pricing.biz.f2": "10.000 KI-Antworten/Monat",
    "pricing.biz.f3": "Erweiterte Analysen",
    "pricing.biz.f4": "Eigenes Branding",
    "pricing.biz.f5": "Prioritäts-Support",
    "pricing.biz.f6": "Team-Zusammenarbeit",
    "pricing.pro.desc": "Für wachsende Unternehmen mit erweiterten Support- und Skalierungsanforderungen.",
    "pricing.pro.cta": "Jetzt starten",
    "pricing.pro.badge": "Beliebt",
    "pricing.pro.featuresLabel": "Alles in Free",
    "pricing.pro.f1": "3 KI-Widgets",
    "pricing.pro.f2": "2.000 KI-Antworten/Monat",
    "pricing.pro.f3": "AI Summaries",
    "pricing.pro.f4": "Erweiterte Analysen",
    "pricing.pro.f5": "24/7 Prioritäts-Support",
    "pricing.pro.f6": "Eigenes Branding",
    "pricing.pro.f7": "Widget-Größe & Positionskontrolle",
    "pricing.pro.f8": "Team-Zusammenarbeit (bald verfügbar)",
    "pricing.business.name": "Enterprise",
    "pricing.business.desc": "Für Organisationen mit hohem Supportvolumen und individuellen Integrationsanforderungen.",
    "pricing.business.cta": "Vertrieb kontaktieren",
    "pricing.business.featuresLabel": "Alles in Business",
    "pricing.business.f1": "Unbegrenzte Gespräche",
    "pricing.business.f2": "API-Zugang",
    "pricing.business.f3": "Dedizierter Account Manager",
    "pricing.business.f4": "SLA-Garantie",
    "pricing.business.f5": "SSO & erweiterte Sicherheit",
    "pricing.business.f6": "White Labeling",

    "faq.title": "Häufig gestellte Fragen",
    "faq.subtitle": "Schnelle Antworten auf die häufigsten Fragen zu Widjet.",
    "faq.q1": "Was ist Widjet und wie funktioniert es?",
    "faq.a1": "Widjet ist eine SaaS-Plattform, mit der Sie schöne Support- und Verkaufs-Widgets für Ihre Website erstellen können. Sie gestalten Ihr Widget in unserem visuellen Editor, passen jedes Detail an und veröffentlichen es mit einer einzigen Zeile Code — keine Entwickler nötig.",
    "faq.q2": "Wie füge ich ein Widget zu meiner Website hinzu?",
    "faq.a2": "Nachdem Sie Ihr Widget erstellt haben, generieren wir ein einzelnes <script>-Tag. Fügen Sie es irgendwo in den HTML-Code Ihrer Website ein und das Widget erscheint sofort. Es funktioniert mit WordPress, Shopify, Webflow, Squarespace und jeder individuell erstellten Website.",
    "faq.q3": "Kann ich das Erscheinungsbild vollständig anpassen?",
    "faq.a3": "Ja — Farben, Schriftarten, Position, Icons, Animationen und sogar benutzerdefiniertes CSS sind alle konfigurierbar. Bei Pro- und Business-Plänen können Sie auch das Widjet-Branding entfernen.",
    "faq.q4": "Wie funktioniert die KI-gestützte Antwortfunktion?",
    "faq.a4": "Widjets KI liest Ihre Wissensdatenbank und erstellt automatisch Antworten auf häufige Besucherfragen. Sie lernt mit der Zeit und kann Ihren Support-Aufwand um bis zu 60% reduzieren.",
    "faq.q5": "Gibt es einen kostenlosen Plan?",
    "faq.a5": "Absolut. Der Free-Plan umfasst 1 Widget und 100 Gespräche pro Monat — für immer. Keine Kreditkarte erforderlich. Wenn Sie bereit sind, können Sie jederzeit auf Pro oder Business upgraden.",
    "faq.q6": "Kann ich mehrere Widgets auf verschiedenen Seiten verwenden?",
    "faq.a6": "Ja! Bei Pro- und Business-Plänen können Sie unbegrenzt Widgets erstellen, jedes mit eigenem Design und Verhalten. Weisen Sie verschiedene Widgets verschiedenen Seiten oder Domains über ein einziges Dashboard zu.",
    "faq.q7": "Welche Art von Analysen bekomme ich?",
    "faq.a7": "Widjet verfolgt Gesprächsvolumen, Antwortzeiten, Besucherzufriedenheit und Konversionsereignisse. Pro-Pläne umfassen erweiterte Analysen mit Funnel-Aufschlüsselungen und exportierbaren Berichten.",
    "faq.contact": "Nicht gefunden, wonach Sie suchen?",
    "faq.contactLink": "Kontaktieren Sie unser Support-Team",

    "footer.ctaTitle1": "Bereit, Ihre Besucher",
    "footer.ctaTitle2": "einzubinden?",
    "footer.ctaDesc": "Schließen Sie sich über 2.000 Unternehmen an, die Widjet bereits nutzen, um mit ihren Kunden in Kontakt zu treten.",
    "footer.ctaCta": "Kostenlos starten",
    "footer.ctaNote": "Für immer kostenlos. Keine Kreditkarte erforderlich.",
    "footer.madeInEu": "Erstellt und gehostet in der EU 🇪🇺",
    "footer.product": "Produkt",
    "footer.widgetBuilder": "Widget Builder",
    "footer.liveChat": "Live-Chat",
    "footer.analytics": "Analysen",
    "footer.integrations": "Integrationen",
    "footer.resources": "Ressourcen",
    "footer.helpCenter": "Hilfecenter",
    "footer.pricing": "Preise",
    "footer.company": "Unternehmen",
    "footer.security": "Sicherheit",
    "footer.terms": "Nutzungsbedingungen",
    "footer.privacy": "Datenschutzrichtlinie",
    "footer.contact": "Kontakt",
    "footer.widjetFor": "Widjet für",
    "footer.ecommerce": "E-Commerce",
    "footer.smallBusiness": "Kleinunternehmen",
    "footer.agencies": "Agenturen",

    "compare.title": "Pläne und Funktionen",
    "compare.catCore": "Kern",
    "compare.catAdvanced": "Erweitert",
    "compare.catEnterprise": "Enterprise",
    "compare.unlimited": "Unbegrenzt",
    "compare.basic": "Grundlegend",
    "compare.advanced": "Erweitert",
    "compare.aiWidgets": "KI-Widgets",
    "compare.aiResponses": "KI-Antworten / Monat",
    "compare.contactCard": "Kontaktkarte",
    "compare.whatsapp": "WhatsApp-Integration",
    "compare.faq": "FAQ-Bereich",
    "compare.productCarousel": "Produktkarussell",
    "compare.escalate": "Eskalation an Mitarbeiter",
    "compare.aiSummaries": "AI Summaries",
    "compare.analytics": "Analysen",
    "compare.customBranding": "Eigenes Branding",
    "compare.sizePosition": "Widget-Größe & Position",
    "compare.instagram": "Instagram-Integration",
    "compare.googleReviews": "Google Reviews Widget",
    "compare.prioritySupport": "Prioritäts-Support",
    "compare.teamCollab": "Team-Zusammenarbeit",
    "compare.apiAccess": "API-Zugang",
    "compare.accountManager": "Dedizierter Account Manager",
    "compare.sla": "SLA-Garantie",
    "compare.sso": "SSO & erweiterte Sicherheit",
    "compare.whiteLabel": "White Labeling",
  },

  fr: {
    "nav.home": "Accueil",
    "nav.features": "Fonctionnalités",
    "nav.dashboard": "Tableau de bord",
    "nav.pricing": "Tarifs",
    "nav.login": "Connexion",
    "nav.signup": "Commencer",
    "nav.widgetBuilder": "Widget Builder",
    "nav.widgetBuilderDesc": "Interface glisser-déposer pour créer des widgets en quelques minutes",
    "nav.liveChat": "Chat en direct",
    "nav.liveChatDesc": "Engagez vos visiteurs avec des conversations en temps réel",
    "nav.analytics": "Analyses",
    "nav.analyticsDesc": "Suivez l'engagement et les taux de conversion en temps réel",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.privacy": "Confidentialité",
    "nav.terms": "Conditions",

    "hero.badge": "Désormais avec des réponses IA",
    "hero.title1": "Des widgets qui transforment",
    "hero.title2": "vos visiteurs en clients",
    "hero.subtitle": "Créez des widgets no-code pour le chat en direct, les FAQ et les ventes. Personnalisez tout, puis ajoutez-le à n'importe quel site avec une seule ligne de code.",
    "hero.cta": "Commencer gratuitement",
    "hero.note1": "Gratuit pour toujours.",
    "hero.note2": "Pas de carte bancaire.",
    "hero.demo": "Voir la démo en direct",

    "logos.heading": "Utilisé par plus de 200 entreprises dans le monde",

    "features.title1": "Tout ce dont vous avez besoin,",
    "features.title2": "rien de superflu",
    "features.1.title": "Entièrement personnalisable",
    "features.1.desc": "Concevez votre widget parfait avec un éditeur visuel intuitif. Changez les couleurs, polices, mises en page, injectez du CSS et JavaScript personnalisés — personnalisation complète sans code. Prévisualisez chaque modification en temps réel.",
    "features.2.title": "Modèle FAQ",
    "features.2.desc": "Réduisez les demandes de support jusqu'à 40 % avec un widget FAQ intelligent. Ajoutez des questions illimitées, personnalisez le design pour correspondre à votre marque et offrez un self-service instantané — 24h/24, 7j/7.",
    "features.3.title": "Fiches produit",
    "features.3.desc": "Captez l'attention de vos visiteurs avec de superbes fiches produit. Collez simplement un lien vers un produit et nous ferons le reste — de belles fiches, prêtes à convertir en quelques secondes.",

    "dashboard.label": "Tableau de bord",
    "dashboard.title": "Tout au même endroit",
    "dashboard.desc": "Gérez tous vos widgets, conversations et analyses depuis un tableau de bord unique et intuitif.",

    "platform.title": "Intégration instantanée",
    "platform.desc": "Copiez le code du widget et collez-le sur votre site — fonctionne avec toutes les plateformes, sans configuration.",

    "pricing.title": "Des tarifs simples et",
    "pricing.titleFaded": "transparents",
    "pricing.guarantee": "Garantie satisfait ou remboursé 100 %",
    "pricing.saveYearly": "Économisez jusqu'à 20 % avec l'annuel",
    "pricing.priceIn": "Prix en",
    "pricing.monthly": "Payer mensuellement",
    "pricing.yearly": "Payer annuellement",
    "pricing.billedYearly": "Facturé annuellement",
    "pricing.billedMonthly": "Facturé mensuellement",
    "pricing.forever": "pour toujours",
    "pricing.free.name": "Free",
    "pricing.free.desc": "Parfait pour ceux qui veulent démarrer et essayer.",
    "pricing.free.cta": "S'inscrire",
    "pricing.free.featuresLabel": "Fonctionnalités clés :",
    "pricing.free.f1": "1 widget IA",
    "pricing.free.f2": "100 réponses IA/mois",
    "pricing.free.f3": "Thème et couleurs personnalisables",
    "pricing.free.f4": "Fiche contact",
    "pricing.free.f5": "Intégration WhatsApp",
    "pricing.free.f6": "Section FAQ",
    "pricing.free.f7": "Carrousel de produits",
    "pricing.free.f8": "Escalade vers un humain",
    "pricing.free.f9": "Support 24/7 (durée limitée)",
    "pricing.starter.name": "Starter",
    "pricing.starter.desc": "Pour les indépendants et projets personnels",
    "pricing.starter.cta": "Commencer",
    "pricing.starter.featuresLabel": "Tout dans Free",
    "pricing.starter.f1": "3 widgets IA",
    "pricing.starter.f2": "500 réponses IA/mois",
    "pricing.starter.f3": "Analyses de base",
    "pricing.starter.f4": "Intégration Instagram",
    "pricing.starter.f5": "Widget Google Reviews",
    "pricing.pro.name": "Plus",
    "pricing.biz.name": "Business",
    "pricing.biz.desc": "Pour les grandes équipes recherchant un support IA puissant et personnalisable.",
    "pricing.biz.cta": "Commencer",
    "pricing.biz.featuresLabel": "Tout dans Plus",
    "pricing.biz.f1": "10 widgets IA",
    "pricing.biz.f2": "10 000 réponses IA/mois",
    "pricing.biz.f3": "Analyses avancées",
    "pricing.biz.f4": "Branding personnalisé",
    "pricing.biz.f5": "Support prioritaire",
    "pricing.biz.f6": "Collaboration d'équipe",
    "pricing.pro.desc": "Pour les entreprises en croissance nécessitant un support avancé et de la scalabilité.",
    "pricing.pro.cta": "Commencer",
    "pricing.pro.badge": "Populaire",
    "pricing.pro.featuresLabel": "Tout dans Free",
    "pricing.pro.f1": "3 widgets IA",
    "pricing.pro.f2": "2 000 réponses IA/mois",
    "pricing.pro.f3": "AI summaries",
    "pricing.pro.f4": "Analyses avancées",
    "pricing.pro.f5": "Support prioritaire 24/7",
    "pricing.pro.f6": "Branding personnalisé",
    "pricing.pro.f7": "Contrôle taille et position du widget",
    "pricing.pro.f8": "Collaboration d'équipe (bientôt)",
    "pricing.business.name": "Enterprise",
    "pricing.business.desc": "Pour les organisations avec un support à haut volume et des besoins d'intégration sur mesure.",
    "pricing.business.cta": "Contacter les ventes",
    "pricing.business.featuresLabel": "Tout dans Business",
    "pricing.business.f1": "Conversations illimitées",
    "pricing.business.f2": "Accès API",
    "pricing.business.f3": "Gestionnaire de compte dédié",
    "pricing.business.f4": "Garantie SLA",
    "pricing.business.f5": "SSO et sécurité avancée",
    "pricing.business.f6": "White labeling",

    "faq.title": "Questions fréquentes",
    "faq.subtitle": "Réponses rapides aux questions les plus courantes sur Widjet.",
    "faq.q1": "Qu'est-ce que Widjet et comment ça marche ?",
    "faq.a1": "Widjet est une plateforme SaaS qui vous permet de créer de superbes widgets de support et de vente pour votre site web. Vous concevez votre widget dans notre éditeur visuel, personnalisez chaque détail et le publiez avec une seule ligne de code — sans développeur.",
    "faq.q2": "Comment ajouter un widget à mon site ?",
    "faq.a2": "Après avoir créé votre widget, nous générons une seule balise <script>. Collez-la n'importe où dans le HTML de votre site et le widget apparaît instantanément. Il fonctionne avec WordPress, Shopify, Webflow, Squarespace et tout site personnalisé.",
    "faq.q3": "Puis-je entièrement personnaliser l'apparence ?",
    "faq.a3": "Oui — couleurs, polices, position, icônes, animations et même le CSS personnalisé sont tous configurables. Avec les plans Pro et Business, vous pouvez aussi retirer le branding Widjet pour une expérience entièrement white-label.",
    "faq.q4": "Comment fonctionne la réponse IA ?",
    "faq.a4": "L'IA de Widjet lit votre base de connaissances et rédige automatiquement des réponses aux questions courantes des visiteurs. Elle apprend avec le temps et peut réduire votre charge de support jusqu'à 60 %.",
    "faq.q5": "Existe-t-il un plan gratuit ?",
    "faq.a5": "Absolument. Le plan Free comprend 1 widget et 100 conversations par mois — pour toujours. Aucune carte bancaire requise. Quand vous êtes prêt, passez à Pro ou Business à tout moment.",
    "faq.q6": "Puis-je utiliser plusieurs widgets sur différentes pages ?",
    "faq.a6": "Oui ! Avec les plans Pro et Business, vous pouvez créer des widgets illimités, chacun avec son propre design et comportement. Attribuez différents widgets à différentes pages ou domaines depuis un seul tableau de bord.",
    "faq.q7": "Quel type d'analyses puis-je obtenir ?",
    "faq.a7": "Widjet suit le volume des conversations, les temps de réponse, la satisfaction des visiteurs et les événements de conversion. Les plans Pro incluent des analyses avancées avec des entonnoirs et des rapports exportables.",
    "faq.contact": "Vous ne trouvez pas ce que vous cherchez ?",
    "faq.contactLink": "Contactez notre équipe support",

    "footer.ctaTitle1": "Prêt à engager",
    "footer.ctaTitle2": "vos visiteurs ?",
    "footer.ctaDesc": "Rejoignez plus de 2 000 entreprises qui utilisent déjà Widjet pour se connecter avec leurs clients.",
    "footer.ctaCta": "Commencer gratuitement",
    "footer.ctaNote": "Gratuit pour toujours. Pas de carte bancaire requise.",
    "footer.madeInEu": "Créé et hébergé dans l'UE 🇪🇺",
    "footer.product": "Produit",
    "footer.widgetBuilder": "Widget Builder",
    "footer.liveChat": "Chat en direct",
    "footer.analytics": "Analyses",
    "footer.integrations": "Intégrations",
    "footer.resources": "Ressources",
    "footer.helpCenter": "Centre d'aide",
    "footer.pricing": "Tarifs",
    "footer.company": "Entreprise",
    "footer.security": "Sécurité",
    "footer.termsPrivacy": "Conditions et confidentialité",
    "footer.contact": "Contact",
    "footer.widjetFor": "Widjet pour",
    "footer.ecommerce": "E-commerce",
    "footer.smallBusiness": "Petites entreprises",
    "footer.agencies": "Agences",

    "compare.title": "Plans et fonctionnalités",
    "compare.catCore": "Essentiel",
    "compare.catAdvanced": "Avancé",
    "compare.catEnterprise": "Enterprise",
    "compare.unlimited": "Illimité",
    "compare.basic": "Basique",
    "compare.advanced": "Avancé",
    "compare.aiWidgets": "Widgets IA",
    "compare.aiResponses": "Réponses IA / mois",
    "compare.contactCard": "Fiche contact",
    "compare.whatsapp": "Intégration WhatsApp",
    "compare.faq": "Section FAQ",
    "compare.productCarousel": "Carrousel de produits",
    "compare.escalate": "Escalade vers un humain",
    "compare.aiSummaries": "AI summaries",
    "compare.analytics": "Analyses",
    "compare.customBranding": "Branding personnalisé",
    "compare.sizePosition": "Taille et position du widget",
    "compare.instagram": "Intégration Instagram",
    "compare.googleReviews": "Widget Google Reviews",
    "compare.prioritySupport": "Support prioritaire",
    "compare.teamCollab": "Collaboration d'équipe",
    "compare.apiAccess": "Accès API",
    "compare.accountManager": "Gestionnaire de compte dédié",
    "compare.sla": "Garantie SLA",
    "compare.sso": "SSO et sécurité avancée",
    "compare.whiteLabel": "White labeling",
  },
};

export const LandingLanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<LandingLang>(() => detectLanguage());

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LandingLanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LandingLanguageContext.Provider>
  );
};
